### ISSUE TITLE
AGP 8+的适配计划有吗，我最近在处理，可以PR上来。

### ISSUE THREAD

**Issue by 5peak2me** [xiazunyang/discovery#3]
哈喽，我之前有针对AGP7.4+的适配写了文章[Transform API 废弃了，路由插件怎么办？](https://juejin.cn/post/7222091234100330554)，目前正在处理该库，作者是否有计划适配，或者接受PR。

**Comment by xiazunyang** [comment]
计划是有，但是工作忙，还腾不出手来处理，能提交PR上来的话，我是完全欢迎的！

**Comment by xiazunyang** [comment]
已适配 Gradle 8.0，感谢关注。
